language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
env:
  - MOZ_HEADLESS=1
script:
  - bash -c 'GLOBIGNORE="node_modules" shellcheck **/*.sh'
  - npm install
  - npm run test
  - npm run lint
  - bash -c '"$(npm bin)/tslint" --project .'

notifications:
  webhooks:
    urls:
      - secure: JMDwcT11GIiLITD48xmVzJtncMPBr/EU0BXCn30oD/i/+tYnAlg/08/6zf22x08cy34saxDEy4+fQnpRG1ConITb2eAGvh2olTuQCIGUYMQvGzd5BX23keNe7VbflJrKKRdbhOZ0wPJRb7mUPbtFbKlAl35WnGMaf/3Dz1yfAx/znBVmAoPQ0LN+VLfp2KzIFAclWhtZluJjbKgFixZCbrS/6tQruYQnWN2+6LPR+jcxltpQaRsXy6HGg9kGGPZCBbPOVZl5PCpkrFCilzD4OQTy7Vc9i5xFBIM9lVDA5/K5l4eEtAMcvCHUz2HdGyJwK5eAPYVeXZYjIdrEEbjxstUuj1Y6aCJYuJAb9wKYCELRDP4XXl/8qR0QUF3VrvADe0tsaYzJow/CvzZ7/8zEzYmn0FO27BC/7mQBgMROucswbRD/BEAkZwXtk5CFFTffZX+daZ1Kfe8uAGlnCPZQWeUUmsiLe34VbKjEjzQ2aP7K+0vHgQQUtxoA2Cey6N90PCSMFklHDAy2Rv+7aPUXNu+zOFSmPhurL0/P5cu3uovHWitc+gEd1mGHSY5XIe+n2zz1bY6j9sx4O8mEhTBRRDTOSIbmv8kEhVcTvy3FQdyw5NYCTkdjy6MNLHXtjsQjTZmY72o3ZtaSxQCEAQ3c1SLUGpnpqx2qPb7t8mxuiSc=
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
addons:
  firefox: "latest-unsigned"
